### ISSUE TITLE
fci-mode breaks popup-el

### ISSUE THREAD

**Issue by Eilie** [alpaker/fill-column-indicator#60] opened 2015-06-30 18:05 UTC
For some reason flycheck compilation error popup can't be displayed over text so it chooses to add each line of compilation error popup at the end of existing line:
![](http://i.imgur.com/ETbqtzl.png)

Disabling `fci-mode` fixes issue, would be great to make `fci-mode`  work properly with `popup-el` tho.

**Comment by eigengrau** [comment] 2015-09-08 10:59
Dupe of #21.

**Comment by alpaker** [comment] 2019-01-29 16:42
Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer.

**Comment by alpaker** [comment] 2020-08-06 22:31
The functionality provided by this package has now been implemented natively in Emacs as `display-fill-column-indicator-mode`, available as of version 27.0.90. Unless you are forced to use an older Emacs, you should use the native implementation instead of `fci-mode`. The former is unaffected by most of the compatibility issues that this add-on has.

**Closed by alpaker** 2020-08-06 22:31 UTC
